# -*- coding: utf-8 -*-
"""Gradio_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWtqNUZmgAs7pup3MgL5KYqpQqWiPuDT
"""

!pip install gradio

def recommend_titles_only(book_title):
    result = get_recommends(book_title)
    if isinstance(result, str):
        return result  # error message
    recommended_books = result[1]
    return [book for book, score in recommended_books]

import gradio as gr

def recommend_titles_only(book_title):
    result = get_recommends(book_title)
    if isinstance(result, str):
        return result
    recommended_books = result[1]
    return [book for book, score in recommended_books]

book_list = [  # Replace this with your dynamic list if available
    "Where the Heart Is (Oprah's Book Club (Paperback))",
    "The Lovely Bones: A Novel",
    "Harry Potter and the Sorcerer's Stone (Book 1)",
    "The Da Vinci Code"
]

interface = gr.Interface(
    fn=recommend_titles_only,
    inputs=gr.Dropdown(book_list, label="Choose a book"),
    outputs=gr.Textbox(label="Recommended Books"),
    title="📚 Book Recommendation Engine"
)

interface.launch()